language: java
jdk:
  - openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "kiwiproject"
    token:
      secure: "HVDkhOWw4mUd4Ec1jXQDDcGBpJPPg4pZ0B/5a7W3VXyXZqmuSfh/Wu7XOM1P3jLGy/p7tJ79LwHILjA1bJryminsG0aFx4TYVv/m75AhsLHaYq85DKjiJpi/bbMXDXIROQZO1TSNS11GZgNPQsA47fLPly4t9bXLF73VWQffYIk9WDfmewxMz3zPlWhazGGuyFjAT5jRJd8p7QdKW9RW8EH+PLZTjtALSVZabXAoeBKvZJlG/tvszaKAearbjPFGwFlHAnIPlCxG1/1IeFmO3tWltJSxxtYORm2ejG2uKoqvfMU8VKS4diPoYkEwz7cnU6EYpI0bKgqNr8gbgiU4qOM++OfPjfFixlKL/uR0NS26veUuvLblGrAnw5rahTY3yfZDJoLEcS/yi5W25BY1XeXAJls/LavtWavTFQQvzTmiTYWp/8AvB5nU4ZgP5Fj4pfpX5Xri7iWH9bRZL78C6jNjdkYHz71Om0mRtPtOtcs/YXd9Izq//tM4Vm+5Pp4+f4A+6SZvvgzGvR+4AHwE1eUq7B0iu+QWLd/QgNK/P0VyaXVUFDT2ntr1233Z+xmcR6FKpuv1Ljm1tmTyrzW6E5dgXIizix8MYH3oLuUFurVGwuX7s3J1uLyS6b15RPCqTpBU8Rnku4zavBgQwZUc9hZD/FBIa2tpTt8TZihRxOA="

script:
  - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent
    package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=kiwiproject_metrics-healthchecks-severity
